# Generated by Django 2.2.16 on 2022-06-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220619_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
