# Generated by Django 2.2.16 on 2022-06-26 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20220619_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikes',
            name='post',
        ),
        migrations.AddField(
            model_name='commentlikes',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentlikes', to='posts.Comment', verbose_name='Лайк коммента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentlikes',
            name='like_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentlikes', to=settings.AUTH_USER_MODEL, verbose_name='Автор лайка коммента'),
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(verbose_name='Лайк')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время лайка')),
                ('like_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlikes', to=settings.AUTH_USER_MODEL, verbose_name='Автор лайка поста')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlikes', to='posts.Post', verbose_name='Лайк поста')),
            ],
        ),
    ]
