# Generated by Django 2.2.16 on 2022-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220630_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='commentlikes',
            name='like',
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='like',
        ),
        migrations.AddField(
            model_name='commentlikes',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=10, verbose_name='Лайк'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=10, verbose_name='Лайк'),
        ),
    ]
