# Generated by Django 2.2.16 on 2022-06-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_auto_20220630_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.ManyToManyField(blank=True, default=None, related_name='postsunlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='postslike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DisLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Dislike', max_length=10, verbose_name='Дизлайк')),
                ('dislike_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postdislikes', to=settings.AUTH_USER_MODEL, verbose_name='Автор дизлайка поста')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postdislikes', to='posts.Post', verbose_name='Дизлайк поста')),
            ],
            options={
                'verbose_name': 'Дизлайк поста',
                'verbose_name_plural': 'Дизлайки постов',
            },
        ),
    ]
