# Generated by Django 2.2.16 on 2022-06-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220630_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
