# Generated by Django 2.2.16 on 2022-06-30 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20220630_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='disliked',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='postsunlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='postslike', to=settings.AUTH_USER_MODEL),
        ),
    ]
