# Generated by Django 2.2.16 on 2022-06-30 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0022_auto_20220630_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disliked',
        ),
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.ManyToManyField(default=None, related_name='postsunlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(default=None, related_name='postslike', to=settings.AUTH_USER_MODEL),
        ),
    ]
