# Generated by Django 2.2.16 on 2022-06-30 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0025_remove_post_disliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.ManyToManyField(related_name='postsunlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostDisLikes',
        ),
    ]
