# Generated by Django 2.2.16 on 2022-06-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_postdislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='disliked',
            new_name='dislllliked',
        ),
    ]
