# Generated by Django 2.2.16 on 2022-06-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20220630_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
