# Generated by Django 2.2.16 on 2022-06-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20220630_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDisLike',
        ),
    ]
