# Generated by Django 2.2.16 on 2022-07-01 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0038_auto_20220630_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disliked',
        ),
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
