# Generated by Django 2.2.16 on 2022-07-04 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_auto_20220703_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='comments_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
