# Generated by Django 2.2.16 on 2022-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_auto_20220707_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdislike',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, max_length=10, verbose_name='Дизлайк'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, max_length=10, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='postdislike',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, max_length=10, verbose_name='Дизлайк'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, max_length=10, verbose_name='Лайк'),
        ),
    ]
